### ISSUE TITLE
Look at PostHTML. Maybe create plugin for this?

### ISSUE THREAD

**Issue by voischev** [Rebelmail/html-autoprefixer#15]
https://github.com/posthtml/posthtml

**Comment by motdotla** [comment]
Can you elaborate @voischev. What would be the reason to do this?

**Comment by voischev** [comment]
Support new platform.
That would work with your plugin as working with `postcss` plugins

```
posthtml([
    requare('posthtml-custom-elements'),
    requare('posthtml-include'),
    requare('html-autoprefixer'),
    requare('other-posthtml-plugin')
]).process(html)...

```

**Comment by motdotla** [comment]
Ok, I see what you mean. Definitely considered this, but the goal being for this repo:

`Autoprefix all CSS inside an html page` 

Use postcss right now gets the job done.

Closing this issue.
