### ISSUE TITLE
Nested elements

### ISSUE THREAD

**Issue by elbuo8** [RebelMail/html-autoprefixer#3]
https://github.com/RebelMail/html-autoprefixer/blob/master/lib/main.js#L33

Wouldn't that potentially replace the first "}" it finds rather than the last one?? If there are nested rules wouldn't they get messed up?

**Comment by elbuo8** [comment]
@motdotla

**Comment by motdotla** [comment]
Add a test to show the scenario. Haven't seen this be an issue yet.

**Comment by motdotla** [comment]
When are we doing nested rules in CSS? 

My thoughts have always been that nested CSS rules are bad.

@M-J-Robbins @elbuo8 - thoughts?

**Comment by M-J-Robbins** [comment]
Any media query could be seen as a nested element.

```@media screen and (max-width: 600px){
  .class{
    width:100%;
  }
}```

Also there is a hack for the SVG images that uses nested media queries
https://github.com/RebelMail/email-report/blob/master/emails/email-report/css/svg-css.css#L37

**Comment by motdotla** [comment]
Gotcha. I'll write a test for this scenario and make sure it is not failing.

**Comment by elbuo8** [comment]
You can just delete the last element of the string. (The "}")

#mobilmail




On Wed, Mar 11, 2015 at 8:20 AM -0700, "Mot" <notifications@github.com> wrote:










Gotcha. I'll write a test for this scenario and make sure it is not failing.



On Wed, Mar 11, 2015 at 3:06 AM, M-J-Robbins <notifications@github.com>

wrote:

**Comment by motdotla** [comment]
I think this is not an issue.

I added two tests here - one with nested, and another with the svg nested nested hack.

https://github.com/RebelMail/html-autoprefixer/commit/abd4e1a26394840b02bcd744704fbef9f1b897c3

Closing for now.

**Comment by motdotla** [comment]
Reopening. hmm. these tests passed locally but failed remotely

**Comment by motdotla** [comment]
node module related. changes in an underlying library

**Comment by motdotla** [comment]
Ok, tests fixed up. Passing.
